### ISSUE TITLE
[Bug] App force closes after FLAC download

### ISSUE THREAD

**Issue by FatKiwi** [J05HI/DeezLoadr#31]

**Comment by Tormiasz** [comment]
I've got it too, this is the error

Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at request.then.request.then (/snapshot/DeezLoadr/DeezLoadr.js:0:0)
    at tryCatcher (/snapshot/DeezLoadr/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/snapshot/DeezLoadr/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (/snapshot/DeezLoadr/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/DeezLoadr/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/DeezLoadr/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/snapshot/DeezLoadr/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/snapshot/DeezLoadr/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.__dirname.Async.drainQueues [as _onImmediate] (/snapshot/DeezLoadr/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by jonaaa20** [comment]
Same problem here hmm

**Comment by FatKiwi** [comment]
Ouch, for a moment I thought they already changed the API again. Seems like app crashes with all formats for artist Crowder. Very weird.

**Comment by J05HI** [comment]
Thanks let's see

**Comment by J05HI** [comment]
Fixed partially :)
Only need to take a look at @Tormiasz song (http://www.deezer.com/en/track/126848417)

**Comment by J05HI** [comment]
@FatKiwi @Tormiasz @Tormiasz 
Fixed :)

**Comment by J05HI** [comment]
Fuuuuuck I've forgotten an console.log 🙄
