### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by bascurtiz** [J05HI/DeezLoadr#48]
I was trying to download a playlist (I made with Soundiiz) in FLAC with 348 tracks, but DeezLoadr 1.2.0 automatically shutted down after a while: http://www.deezer.com/en/playlist/3855420846

After some inspection (looking up the last track that was correctly downloaded and figured out the next track in queue/playlist prolly was the one where DeezLoadr exits) it turns out some specific tracks are causing this:
http://www.deezer.com/en/track/102015661
http://www.deezer.com/en/track/87620607
http://www.deezer.com/en/track/87620601
http://www.deezer.com/en/track/110117982

By deleting them from the playlist, downloading went on until the next same error...

See pics aswell:
https://imgur.com/a/vzZ7z

Happens with 320kbps MP3 aswell.

Error-message seems to be the same:
Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at request.then.request.then (C:\snapshot\DeezLoadr\DeezLoadr.js:0:0)
    at tryCatcher (C:\snapshot\DeezLoadr\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (C:\snapshot\DeezLoadr\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\DeezLoadr\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\DeezLoadr\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\DeezLoadr\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\snapshot\DeezLoadr\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\snapshot\DeezLoadr\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.__dirname.Async.drainQueues [as _onImmediate] (C:\snapshot\DeezLoadr\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

OS: Win10 x64

**Comment by J05HI** [comment]
Will look at it :(

**Comment by J05HI** [comment]
Maybe duplicate: [https://github.com/J05HI/DeezLoadr/issues/47](https://github.com/J05HI/DeezLoadr/issues/47)

**Comment by J05HI** [comment]
Could you please take a look at them :)

**Comment by bascurtiz** [comment]
I can replicate whats showing in #34 , see pics down below:
https://imgur.com/a/PSMG1

pic 1) showing downloaded results with Deeloader 2.3.1 (notice the different album for these 2 tracks)
pic 2) when trying to play the preview from the deezer site
pic 3) no error showing in DeezLoadr 1.2.0, but outcomes is indeed 0kB

But in my case, this topic, does show an error, and won't download or make a 0kB file.
That's the main difference.

**Comment by J05HI** [comment]
Okay thank you very much!

**Comment by bascurtiz** [comment]
You're welcome.
When trying with Deezer: Download script 0kB files are downloaded too on the two #34 tracks.

But,
When trying with Deezer: Download script on my examples, they get correctly downloaded.

See pic below:
https://imgur.com/a/F6SNh

**Comment by J05HI** [comment]
@bascurtiz 

Should be fixed now :)
Please report back.

**Comment by bascurtiz** [comment]
Downloaded the newer version here: https://github.com/J05HI/DeezLoadr/blob/master/BUILDS/DeezLoadr-win-x64.exe

No more error! \o/
Though, some tracks stagnate a playlist (like no error, but also no progression)
Will investigate more, see pic below (same playlist as TS):
https://imgur.com/a/6RMJt

**Comment by J05HI** [comment]
# Project moved!
## New project: [https://github.com/J05HI/SMLoadr](https://github.com/J05HI/SMLoadr)
## Please delete all of your forks!!!
## I'll delete this repo soon!
